---
align_societies:
  - Lawful
  - Chaotic
  - Neutral

align_morals:
  - Good
  - Neutral
  - Evil

classes:
  - Barbarian
  - Fighter
  - Ranger
  - Paladin
  - Monk
  - Bard
  - Rogue
  - Wizard
  - Sorceror
  - Warlock
  - Cleric

genders:
  - Male
  - Female

races:
  Human:
    - Calishite
    - Chondathan
    - Damaran
    - Illuskan
    - Mulan
    - Rashemi
    - Shou
    - Tehyrian
    - Turami
  Elf:
    - High
    - Wood
    - Drow
  Dwarf:
    - Hill
    - Mountain
  Gnome:
    - Forest
    - Rock
  Halfling:
    - Lightfoot
    - Stout
  Tiefling:
  Dragonborne:
  Half-Elf:
  Half-Orc:

backgrounds:
  - Acolyte
  - Charlatan
  - Criminal
  - Folk
  - Hero
  - Guild
  - Artisan
  - Hermit
  - Noble
  - Outlander
  - Sage
  - Sailor
  - Soldier
  - Urchin

names:
  ## humans
  Calishite:
    gender:
      male:
        - Aseir
        - Bardeid
        - Haseid
        - Khemed
        - Mehmen
        - Sudeiman
        - Zasheir
      female:
        - Atala
        - Ceidil
        - Hama
        - Jasmal
        - Meilil
        - Seipora
        - Yasheira
        - Zasheida
    last:
        - Basha
        - Dumein
        - Jassan
        - Khalid
        - Mostana
        - Pashar
        - Rein
  Chondathan:
    gender:
      male:
        - Darvin
        - Dorn
        - Evendur
        - Gorstag
        - Grim
        - Helm
        - Malark
        - Morn
        - Randal
        - Stedd
      female:
        - Arveene
        - Esvele
        - Jhessail
        - Kerri
        - Lureene
        - Miri
        - Rowan
        - Shandri
        - Tessele
    surname:
        - Amblecrown
        - Buckman
        - Dundragon
        - Evenwood
        - Greycastle
        - Tallstag
  Damaran:
    gender:
      male:
        - Bor
        - Fodel
        - Glar
        - Grigor
        - Igan
        - Ivor
        - Kosef
        - Mival
        - Orel
        - Pavel
        - Sergor
      female:
        - Alethra
        - Kara
        - Katernin
        - Mara
        - Natali
        - Olma
        - Tana
        - Zora
    surname:
        - Bersk
        - Chernin
        - Dotsk
        - Kulenov
        - Marsk
        - Nemetsk
        - Shemov
        - Starag
  Illuskan:
    gender:
      male:
        - Ander
        - Blath
        - Bran
        - Frath
        - Geth
        - Lander
        - Luth
        - Malcer
        - Stor
        - Taman
        - Urth
      female:
        - Amafrey
        - Betha
        - Cefrey
        - Kethra
        - Mara
        - Olga
        - Silifrey
        - Westra
    surname:
        - Brightwood
        - Helder
        - Hornraven
        - Lackman
        - Stormwind
        - Windrivver
  Mulan:
    gender:
      male:
        - Aoth
        - Bareris
        - Ehput-Ki Kethoth Mumed Ramas So-Kehur Thazar-De Urhur
      female:
        - Arizima
        - Chathi
        - Nephis
        - Nulara
        - Murithi
        - Sefris
        - Thola
        - Umara
        - Zolis
    surname:
        - Ankhalab
        - Anskuld
        - Fezim
        - Hahpet
        - Nathandem
        - Sepret
        - Uuthrakt
  Shou:
    gender:
      male:
        - An
        - Chen
        - Chi
        - Fai
        - Jiang
        - Jun
        - Lian
        - Long
        - Meng
        - On
        - Shan
        - Shui
        - Wen
      female:
        - Bai
        - Chao
        - Jia
        - Lei
        - Mei
        - Qiao
        - Shui
        - Tai
    surname:
        - Chien
        - Huang
        - Kao
        - Kung
        - Lao
        - Ling
        - Mei
        - Pin
        - Shin
        - Sum
        - Tan
        - Wan
  Turami:
    gender:
      male:
        - Anton
        - Diero
        - Marcon
        - Pieron
        - Rimardo
        - Romero
        - Salazar
        - Umbero
      female:
        - Balama
        - Dona
        - Faila
        - Jalana
        - Luisa
        - Marta
        - Quara
        - Selise
        - Vonda
    surname:
      - Agosto
      - Astorio
      - Calabra
      - Domine
      - Falone
      - Marivaldi
      - Pisacar
      - Ramondo

  ## non-humans
  Elf:
    gender:
      male:
        - Adran
        - Aelar
        - Aramil
        - Arannis
        - Aust
        - Beiro
        - Berrian
        - Carric 
        - Enialis
        - Erdan
        - Erevan
        - Galinndan
        - Hadarai
        - Heian
        - Himo
        - Immeral
        - Ivellios
        - Laucian
        - Mindartis
        - Paelias
        - Peren
        - Quarion
        - Riardon
        - Rolen
        - Soveliss
        - Thamior
        - Tharivol
        - Theren
        - Varis
      female:
        - Adrie
        - Althaea
        - Anastrianna
        - Andraste
        - Antinua
        - Bethrynna
        - Birel
        - Caelynn
        - Drusilia
        - Enna
        - Felosial
        - Ielenia
        - Jelenneth
        - Keyleth
        - Leshanna
        - Lia
        - Meriele
        - Mialee
        - Naivara
        - Quelenna
        - Quillathe
        - Sariel
        - Shanairra
        - Shava
        - Silaqui
        - Theirastra
        - Thia
        - Vadania
        - Valanthe
        - Xanaphia
    child:
      - Ara
      - Bryn
      - Del
      - Eryn
      - Faen
      - Innil
      - Lael
      - Mella
      - Naill
      - Naeris
      - Phann
      - Rael
      - Rinn
      - Sai
      - Syllin
      - Thia
      - Vall
    family:
      - Amakiir (Gemflower)
      - Amastacia (Starflower)
      - Galanodel (Moonwhisper)
      - Holimion (Diamonddew)
      - Ilphelkiir (Gemblossom)
      - Liadon (Silverfrond)
      - Meliamne (Oakenheel)
      - Nai''lo (Nightbreeze)
      - Siannodel (Moonbrook)
      - Xiloscient (Goldpetal)

  Dwarf:
    gender:
      male:
          - Adrik
          - Alberich
          - Baern
          - Barendd
          - Brottor
          - Bruenor
          - Dain
          - Darrak
          - Delg
          - Eberk
          - Einkil
          - Fargrim
          - Flint
          - Gardain
          - Harbek
          - Kildrak
          - Morgran
          - Orsik
          - Oskar
          - Rangrim
          - Rurik
          - Taklinn
          - Thoradin
          - Thorin
          - Tordek
          - Traubon
          - Travok
          - Ulfgar
          - Veit
          - Vondal
      female:
          - Amber
          - Artin
          - Audhild
          - Bardryn
          - Dagnal
          - Diesa
          - Eldeth
          - Falkrunn
          - Finellen
          - Gunnloda
          - Gurdis
          - Helja
          - Hlin
          - Kathra
          - Kristryd
          - Ilde
          - Liftrasa
          - Mardred
          - Riswynn
          - Sannl
          - Torbera
          - Torgga
          - Vistra
    clan:
      - Balderk
      - Battlehammer
      - Brawnanvil
      - Dankil
      - Fireforge
      - Frostbeard
      - Gorunn
      - Holderhek
      - Ironfist
      - Loderr
      - Lutgehr
      - Rumnaheim
      - Strakeln
      - Torunn
      - Ungart

  Gnome:
    gender:
      male:
        - Bob
      female:
        - Mary
    last:
      - McSweeny

  Halfling:
    gender:
      male:
        - Alton
        - Ander
        - Cade
        - Corrin
        - Eldon
        - Errich
        - Finnan
        - Garret
        - Lindal
        - Lyle
        - Merric
        - Milo
        - Osborn
        - Perrin
        - Reed
        - Roscoe
        - Wellby
      female:
        - Andry
        - Bree
        - Callie
        - Cora
        - Euphemia
        - Jillian
        - Kithri
        - Lavinia
        - Lidda
        - Merla
        - Nedda
        - Paela
        - Portia
        - Seraphina
        - Shaena
        - Trym
        - Vani
        - Verna
    family:
      - Brushgather
      - Goodbarrel
      - Greenbottle
      - High-hill
      - Hilltopple
      - Leagallow
      - Tealeaf
      - Thorngage
      - Tosscobble
      - Underbough

  Tiefling:
    gender:
      male:
        - Bob
      female:
        - Mary
    last:
      - McSweeny

  Dragonborne:
    gender:
      male:
        - Bob
      female:
        - Mary
    last:
      - McSweeny

  Half-Elf:
    gender:
      male:
        - Bob
      female:
        - Mary
    last:
      - McSweeny

  Half-Orc:
    gender:
      male:
        - Bob
      female:
        - Mary
    last:
      - McSweeny

